### ISSUE TITLE
Ability to tie Slack username with IRC username

### ISSUE THREAD

**Issue by lewiscowper** [hoodiehq/slack-irc-duplex#1]
This is a big one, so feel free to tell me that it's not happening, but it would be cool if for a registered user, you could set an option somewhere that links your slack username to your IRC nick (the IRC realname or username being identical to the slack username for example).

Then when messages are pulled through from slack -> IRC, it'd be cool if the usernames were mimicked somehow, rather than slackbot2 <username> message.

That last bit might be complete with my non-understanding of how the IRC protocol works and stuff, but it'd be cool for IRC highlights for lewiscowper could highlight lewis for example.

**Comment by boennemann** [comment]
Sorry for leaving this unanswered for so long.

The logic wouldn't be to complicated, but that would add the requirement of a persistence layer and probably some to UI to this still minimalistic script. I think I won't do it in the near future, but I'm happy to assist anyone who wants to.
