### ISSUE TITLE
IRC messages beginning with /me don't get transferred through

### ISSUE THREAD

**Issue by lewiscowper** [hoodiehq/slack-irc-duplex#2]
![tumblr_ljm1hmwgyp1qhaufl](https://cloud.githubusercontent.com/assets/593574/6084645/a3b7c1d8-ae2a-11e4-9d77-496f8568bd13.gif)

**Comment by boennemann** [comment]
https://github.com/hoodiehq/slack-irc-duplex/commit/9c8be50b4abd358d2b8f86b6919f98bccba8b8c3 :)
