### ISSUE TITLE
links get truncated

### ISSUE THREAD

**Issue by janl** [hoodiehq/slack-irc-duplex#3]
Slack message:

> @thartmann: is this you? https://github.com/thartmann

becomes

> [11:41:58]  <slackbot3>    <jan> @thartmann: is this you? <https://github.com/`

**Comment by boennemann** [comment]
Probably related to this beast: https://github.com/hoodiehq/slack-irc-duplex/blob/master/index.js#L43
Do you have any idea why @janl?

**Comment by janl** [comment]
would have run some sample data through the regex.

Give me some time :)

**Comment by janl** [comment]
set up slack-irc, I think we can retire this
